/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Admin
 */
public class DaiLy extends javax.swing.JInternalFrame {

    /**
     * Creates new form DaiLy
     */
    public DaiLy() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        tblDaiLy.getTableHeader().setOpaque(false);
        tblDaiLy.getTableHeader().setBackground(new Color(51, 30, 247));
        tblDaiLy.getTableHeader().setForeground(new Color(0, 0, 0));
        tblDaiLy.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDaiLy = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaiLy = new javax.swing.JTable();
        lblMaDaiLy = new javax.swing.JLabel();
        lblTenDaiLy = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtMaDaiLy = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        lblGhiChu = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pnlTieuDe = new javax.swing.JPanel();
        lblDaiLy = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1430, 910));

        pnlDaiLy.setBackground(new java.awt.Color(255, 255, 255));

        tblDaiLy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblDaiLy.setForeground(new java.awt.Color(0, 0, 0));
        tblDaiLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ ĐẠI LÝ", "TÊN ĐẠI LÝ", "SĐT", "ĐỊA CHỈ", "EMAIL", "GHI CHÚ"
            }
        ));
        tblDaiLy.setFocusable(false);
        tblDaiLy.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDaiLy.setRowHeight(25);
        tblDaiLy.setSelectionBackground(new java.awt.Color(0, 102, 153));
        tblDaiLy.setShowVerticalLines(false);
        tblDaiLy.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDaiLy);

        lblMaDaiLy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMaDaiLy.setForeground(new java.awt.Color(0, 0, 0));
        lblMaDaiLy.setText("MÃ ĐẠI LÝ");

        lblTenDaiLy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTenDaiLy.setForeground(new java.awt.Color(0, 0, 0));
        lblTenDaiLy.setText("TÊN ĐẠI LÝ");

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("EMAIL");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));

        txtTen.setBackground(new java.awt.Color(204, 204, 204));
        txtTen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTen.setForeground(new java.awt.Color(0, 0, 0));
        txtTen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));

        txtMaDaiLy.setBackground(new java.awt.Color(204, 204, 204));
        txtMaDaiLy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMaDaiLy.setForeground(new java.awt.Color(0, 0, 0));
        txtMaDaiLy.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaDaiLy.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));

        lblSDT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 0));
        lblSDT.setText("SỐ ĐIỆN THOẠI");

        lblDiaChi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        lblDiaChi.setText("ĐỊA CHỈ");

        txtSDT.setBackground(new java.awt.Color(204, 204, 204));
        txtSDT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(0, 0, 0));
        txtSDT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));

        txtDiaChi.setBackground(new java.awt.Color(204, 204, 204));
        txtDiaChi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));

        txtGhiChu.setBackground(new java.awt.Color(204, 204, 204));
        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(0, 0, 0));
        txtGhiChu.setRows(5);
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 153)));
        txtGhiChu.setFocusable(false);
        jScrollPane2.setViewportView(txtGhiChu);

        lblGhiChu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 0));
        lblGhiChu.setText("GHI CHÚ");

        btnThem.setBackground(new java.awt.Color(0, 102, 153));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_50px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setBorder(null);

        btnSua.setBackground(new java.awt.Color(255, 204, 51));
        btnSua.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_maintenance_50px.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setBorder(null);

        btnXoa.setBackground(new java.awt.Color(255, 0, 51));
        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_50px.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(null);

        btnThoat.setBackground(new java.awt.Color(0, 204, 51));
        btnThoat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_rewind_50px.png"))); // NOI18N
        btnThoat.setText("XÓA");
        btnThoat.setBorder(null);

        pnlTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        pnlTieuDe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 153)));
        pnlTieuDe.setForeground(new java.awt.Color(0, 102, 153));
        pnlTieuDe.setPreferredSize(new java.awt.Dimension(404, 50));

        lblDaiLy.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDaiLy.setForeground(new java.awt.Color(0, 102, 153));
        lblDaiLy.setText("THÔNG TIN ĐẠI LÝ");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDaiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDaiLy, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDaiLyLayout = new javax.swing.GroupLayout(pnlDaiLy);
        pnlDaiLy.setLayout(pnlDaiLyLayout);
        pnlDaiLyLayout.setHorizontalGroup(
            pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 1420, Short.MAX_VALUE)
            .addGroup(pnlDaiLyLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaiLyLayout.createSequentialGroup()
                        .addComponent(lblMaDaiLy)
                        .addGap(359, 359, 359)
                        .addComponent(lblTenDaiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDaiLyLayout.createSequentialGroup()
                        .addComponent(txtMaDaiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDaiLyLayout.createSequentialGroup()
                        .addComponent(lblSDT)
                        .addGap(327, 327, 327)
                        .addComponent(lblDiaChi))
                    .addGroup(pnlDaiLyLayout.createSequentialGroup()
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDaiLyLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(750, 750, 750)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlDaiLyLayout.setVerticalGroup(
            pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaiLyLayout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaDaiLy)
                    .addComponent(lblTenDaiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDaiLy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSDT)
                    .addComponent(lblDiaChi))
                .addGap(11, 11, 11)
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaiLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDaiLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDaiLy;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblMaDaiLy;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenDaiLy;
    private javax.swing.JPanel pnlDaiLy;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JTable tblDaiLy;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaDaiLy;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
