/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import GUI.frmMain;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class frmLogin extends javax.swing.JFrame {

    Color buttondefault;

    public frmLogin() {
        initComponents();
        this.getRootPane().setDefaultButton(btnSignup);
        buttondefault = new Color(0, 102, 153);
        btnSignup.setBackground(buttondefault);
        show.setVisible(true);
        show.setEnabled(true);
        dis.setVisible(false);
        dis.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTong = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        btnSignup = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        sptMatKhau = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        lblThoat = new javax.swing.JLabel();
        sptTenDN = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        lblName = new javax.swing.JLabel();
        ckbRemember = new javax.swing.JCheckBox();
        lblForget = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));
        pnlTong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignup.setBackground(new java.awt.Color(0, 102, 153));
        btnSignup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("ĐĂNG NHẬP");
        btnSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        pnlRight.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, 40));

        lblPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPass.setForeground(new java.awt.Color(51, 51, 51));
        lblPass.setText("MẬT KHẨU");
        pnlRight.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, -1));
        pnlRight.add(sptMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 310, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setText("ADMIN");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlRight.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 310, 30));

        lblThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(204, 204, 0));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_sign_30px_1.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlRight.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 30, 30));
        pnlRight.add(sptTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 310, -1));

        txtPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPass.setText("admin");
        txtPass.setBorder(null);
        txtPass.setEchoChar((char)8226);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        pnlRight.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 260, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 153));
        lblName.setText("TÊN ĐĂNG NHẬP");
        pnlRight.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, -1));

        ckbRemember.setBackground(new java.awt.Color(255, 255, 255));
        ckbRemember.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ckbRemember.setForeground(new java.awt.Color(51, 51, 51));
        ckbRemember.setSelected(true);
        ckbRemember.setText("Ghi Nhớ");
        pnlRight.add(ckbRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        lblForget.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblForget.setForeground(new java.awt.Color(51, 51, 51));
        lblForget.setText("Quên Mật Khẩu");
        pnlRight.add(lblForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, 20));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_male_circle_100px.png"))); // NOI18N
        pnlRight.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        dis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_visible_25px.png"))); // NOI18N
        dis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disMouseClicked(evt);
            }
        });
        pnlRight.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 40));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_hide_25px.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        pnlRight.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 40));

        pnlTong.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 0, 475, 500));

        jLabel4.setBackground(new java.awt.Color(1, 91, 126));
        jLabel4.setFont(new java.awt.Font("Dosis", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("dienmayvituan.vn");
        jLabel4.setOpaque(true);
        pnlTong.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 160, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled-1.png"))); // NOI18N
        pnlTong.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        //txtPass.setText("");
    }//GEN-LAST:event_txtPassMouseClicked

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        lblPass.setForeground(new Color(0, 102, 153));
        lblName.setForeground(new Color(51, 51, 51));
        txtPass.setForeground(new Color(0, 102, 153));
        txtName.setForeground(new Color(51, 51, 51));
//        sptMatKhau.setBackground(new Color(204, 204, 0));
//        sptTenDN.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_txtPassFocusGained

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        int nutBam = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát không", "Xác nhận thoát chương trình", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (nutBam == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblThoatMouseClicked

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        //txtName.setText("");
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        lblName.setForeground(new Color(0, 102, 153));
        lblPass.setForeground(new Color(51, 51, 51));
        txtName.setForeground(new Color(0, 102, 153));
        txtPass.setForeground(new Color(51, 51, 51));
        sptTenDN.setForeground(new Color(0, 102, 153));
        //        sptMatKhau.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_txtNameFocusGained

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        this.dispose();
        frmMain frm = new frmMain();
        frm.setVisible(true);
    }//GEN-LAST:event_btnSignupActionPerformed

    private void disMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disMouseClicked
        show.setVisible(true);
        show.setEnabled(true);
        txtPass.setEchoChar((char)8226);
        dis.setVisible(false);
        dis.setEnabled(false);
    }//GEN-LAST:event_disMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        dis.setVisible(true);
        dis.setEnabled(true);
        txtPass.setEchoChar((char)0);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JCheckBox ckbRemember;
    private javax.swing.JLabel dis;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblForget;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTong;
    private javax.swing.JLabel show;
    private javax.swing.JSeparator sptMatKhau;
    private javax.swing.JSeparator sptTenDN;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
