/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DBConnection;
import SP.GUI.page_Main_NhapHang;
import SP.GUI.page_ViTri;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
//import sun.util.locale.provider.SPILocaleProviderAdapter;

/**
 *
 * @author Admin
 */
public class frmMain extends javax.swing.JFrame {

    //Phóng to màn hình
    static boolean maximized = true;

    public static Color paneDefault = new Color(6, 114, 168);//Màu mặc định
    public static Color paneClick = new Color(0, 56, 84);//Màu sau khi click
    public static Color paneHover = new Color(4, 134, 198);
    //Màu khi rê chuột
    public static Color entercolor = new Color(4, 134, 198);
    //khi thoát ra không rê nữa
    public static Color exitcolor = new Color(6, 114, 168);

// Các page trong phần sản phẩm:
    
    public static SP.GUI.page_Main_NhapHang pageMain;
    public static SP.GUI.page_ViTri vitri;
    
    
    public frmMain() {
        initComponents();
        DBConnection conn = new DBConnection();
        clock();
//        pnlHome.setBackground(paneDefault);
//        pane2.setBackground(paneDefault);
        Home mau = new Home();
        dkpRight.add(mau).setVisible(true);
        pnlHome.setBackground(paneClick);

        //Tạo đồng hồ
    }

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR_OF_DAY);
                        String gio;
                        String giay;
                        String phut;
                        String thu;
                        String buoi;
                        int dayOfWeek = cal.get(Calendar.DAY_OF_WEEK);
                        if (dayOfWeek == 1) {
                            thu = "Chủ nhật";
                        } else {
                            thu = "Thứ " + Integer.toString(dayOfWeek);
                        }
                        if (minute < 10) {
                            phut = "0" + minute;
                        } else {
                            phut = String.valueOf(minute);
                        }

                        if (hour < 10) {
                            gio = "0" + hour;
                        } else {
                            gio = String.valueOf(hour);
                        }
                        if (second < 10) {
                            giay = "0" + second;
                        } else {
                            giay = String.valueOf(second);
                        }
                        if (Integer.parseInt(gio) >= 13) {
                            buoi = "PM";
                        } else {
                            buoi = "AM";
                        }
                        lblTime.setText(gio + ":" + phut + ":" + giay + " " + buoi);
                        sleep(1000);
                        Calendar now = Calendar.getInstance();
                        Home.lblThongTinHome.setText("Xin chào!, hôm nay là ngày " + now.get(Calendar.DATE) + "-" + (now.get(Calendar.MONTH) + 1) + "-" + now.get(Calendar.YEAR));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTong = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblLogoViTuan = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        lblIconBanHang = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        pnlBanHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        pnlKhachHang = new javax.swing.JPanel();
        lblIconKH = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        pnlDaiLy = new javax.swing.JPanel();
        lblIconDaiLy = new javax.swing.JLabel();
        lblDaiLy = new javax.swing.JLabel();
        pnlKho = new javax.swing.JPanel();
        lblIconKho = new javax.swing.JLabel();
        lblKho = new javax.swing.JLabel();
        pnlDoanhThu = new javax.swing.JPanel();
        lblIconDoanhThu = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        pnlBaoHanh = new javax.swing.JPanel();
        lblIconBaoHanh = new javax.swing.JLabel();
        lblBaoHanh = new javax.swing.JLabel();
        pnlTaiKhoan = new javax.swing.JPanel();
        lblIconTaiKhoan = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        pnlLuong = new javax.swing.JPanel();
        lblIconLuong = new javax.swing.JLabel();
        lblLuong = new javax.swing.JLabel();
        pnlSanPham = new javax.swing.JPanel();
        lblIconDoanhThu1 = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        dkpRight = new javax.swing.JDesktopPane();
        pnlTop = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlThaoTac = new javax.swing.JPanel();
        btnXuong = new javax.swing.JButton();
        btnFull = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblTenNguoiDung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1768, 960));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));
        pnlTong.setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(0, 102, 153));
        pnlMenu.setPreferredSize(new java.awt.Dimension(350, 0));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoViTuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        pnlMenu.add(lblLogoViTuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        pnlHome.setBackground(new java.awt.Color(0, 56, 84));
        pnlHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHome.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHomeMousePressed(evt);
            }
        });

        lblIconBanHang.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_30px_1.png"))); // NOI18N

        lblHome.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("Home");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblIconBanHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHome)
                .addGap(0, 203, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHome)
                    .addComponent(lblIconBanHang))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 350, -1));

        pnlBanHang.setBackground(new java.awt.Color(6, 114, 168));
        pnlBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBanHang.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBanHangMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_land_sales_30px.png"))); // NOI18N

        lblBanHang.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblBanHang.setForeground(new java.awt.Color(255, 255, 255));
        lblBanHang.setText("Bán Hàng");

        javax.swing.GroupLayout pnlBanHangLayout = new javax.swing.GroupLayout(pnlBanHang);
        pnlBanHang.setLayout(pnlBanHangLayout);
        pnlBanHangLayout.setHorizontalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBanHang)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        pnlBanHangLayout.setVerticalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBanHang)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, -1));

        pnlKhachHang.setBackground(new java.awt.Color(6, 114, 168));
        pnlKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlKhachHang.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlKhachHangMousePressed(evt);
            }
        });

        lblIconKH.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_queue_30px_1.png"))); // NOI18N

        lblKhachHang.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lblKhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhachHangLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKhachHang)
                .addGap(0, 154, Short.MAX_VALUE))
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKhachHang)
                    .addComponent(lblIconKH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 350, -1));

        pnlDaiLy.setBackground(new java.awt.Color(6, 114, 168));
        pnlDaiLy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDaiLy.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlDaiLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDaiLyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDaiLyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDaiLyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDaiLyMousePressed(evt);
            }
        });

        lblIconDaiLy.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconDaiLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_shop_30px.png"))); // NOI18N

        lblDaiLy.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDaiLy.setForeground(new java.awt.Color(255, 255, 255));
        lblDaiLy.setText("Đại Lý");

        javax.swing.GroupLayout pnlDaiLyLayout = new javax.swing.GroupLayout(pnlDaiLy);
        pnlDaiLy.setLayout(pnlDaiLyLayout);
        pnlDaiLyLayout.setHorizontalGroup(
            pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaiLyLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconDaiLy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDaiLy)
                .addGap(0, 201, Short.MAX_VALUE))
        );
        pnlDaiLyLayout.setVerticalGroup(
            pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaiLyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDaiLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDaiLy)
                    .addComponent(lblIconDaiLy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlDaiLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 350, -1));

        pnlKho.setBackground(new java.awt.Color(6, 114, 168));
        pnlKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlKho.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlKhoMousePressed(evt);
            }
        });

        lblIconKho.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_warehouse_30px.png"))); // NOI18N

        lblKho.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblKho.setForeground(new java.awt.Color(255, 255, 255));
        lblKho.setText("Kho -  Lô & Nhà Cung Cấp");

        javax.swing.GroupLayout pnlKhoLayout = new javax.swing.GroupLayout(pnlKho);
        pnlKho.setLayout(pnlKhoLayout);
        pnlKhoLayout.setHorizontalGroup(
            pnlKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconKho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKho)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        pnlKhoLayout.setVerticalGroup(
            pnlKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKho)
                    .addComponent(lblIconKho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 350, -1));

        pnlDoanhThu.setBackground(new java.awt.Color(6, 114, 168));
        pnlDoanhThu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDoanhThu.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMousePressed(evt);
            }
        });

        lblIconDoanhThu.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_bullish_30px.png"))); // NOI18N

        lblDoanhThu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThu.setText("Doanh thu");

        javax.swing.GroupLayout pnlDoanhThuLayout = new javax.swing.GroupLayout(pnlDoanhThu);
        pnlDoanhThu.setLayout(pnlDoanhThuLayout);
        pnlDoanhThuLayout.setHorizontalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconDoanhThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDoanhThu)
                .addGap(0, 169, Short.MAX_VALUE))
        );
        pnlDoanhThuLayout.setVerticalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDoanhThu)
                    .addComponent(lblIconDoanhThu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 350, -1));

        pnlBaoHanh.setBackground(new java.awt.Color(6, 114, 168));
        pnlBaoHanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBaoHanh.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMousePressed(evt);
            }
        });

        lblIconBaoHanh.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconBaoHanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_guarantee_30px.png"))); // NOI18N

        lblBaoHanh.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblBaoHanh.setForeground(new java.awt.Color(255, 255, 255));
        lblBaoHanh.setText("Bảo Hành");

        javax.swing.GroupLayout pnlBaoHanhLayout = new javax.swing.GroupLayout(pnlBaoHanh);
        pnlBaoHanh.setLayout(pnlBaoHanhLayout);
        pnlBaoHanhLayout.setHorizontalGroup(
            pnlBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaoHanhLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconBaoHanh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBaoHanh)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        pnlBaoHanhLayout.setVerticalGroup(
            pnlBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaoHanhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBaoHanh)
                    .addComponent(lblIconBaoHanh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlBaoHanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 350, -1));

        pnlTaiKhoan.setBackground(new java.awt.Color(6, 114, 168));
        pnlTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTaiKhoan.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTaiKhoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTaiKhoanMousePressed(evt);
            }
        });

        lblIconTaiKhoan.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_male_circle_30px.png"))); // NOI18N

        lblTaiKhoan.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setText("Nhân Viên & Tài Khoản - Quyền");

        javax.swing.GroupLayout pnlTaiKhoanLayout = new javax.swing.GroupLayout(pnlTaiKhoan);
        pnlTaiKhoan.setLayout(pnlTaiKhoanLayout);
        pnlTaiKhoanLayout.setHorizontalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaiKhoanLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTaiKhoan)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        pnlTaiKhoanLayout.setVerticalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTaiKhoan)
                    .addComponent(lblIconTaiKhoan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 350, -1));

        pnlLuong.setBackground(new java.awt.Color(6, 114, 168));
        pnlLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLuong.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLuongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLuongMousePressed(evt);
            }
        });

        lblIconLuong.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_paycheque_30px.png"))); // NOI18N

        lblLuong.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblLuong.setText("Lương");

        javax.swing.GroupLayout pnlLuongLayout = new javax.swing.GroupLayout(pnlLuong);
        pnlLuong.setLayout(pnlLuongLayout);
        pnlLuongLayout.setHorizontalGroup(
            pnlLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLuongLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLuong)
                .addGap(0, 196, Short.MAX_VALUE))
        );
        pnlLuongLayout.setVerticalGroup(
            pnlLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLuong)
                    .addComponent(lblIconLuong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 350, -1));

        pnlSanPham.setBackground(new java.awt.Color(6, 114, 168));
        pnlSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSanPham.setPreferredSize(new java.awt.Dimension(164, 61));
        pnlSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlSanPhamMousePressed(evt);
            }
        });

        lblIconDoanhThu1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        lblIconDoanhThu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_bullish_30px.png"))); // NOI18N

        lblSanPham.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(255, 255, 255));
        lblSanPham.setText("Sản phẩm");

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblIconDoanhThu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSanPham)
                .addGap(0, 172, Short.MAX_VALUE))
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSanPham)
                    .addComponent(lblIconDoanhThu1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 350, -1));

        pnlTong.add(pnlMenu, java.awt.BorderLayout.LINE_START);

        dkpRight.setBackground(new java.awt.Color(255, 255, 255));
        dkpRight.setLayout(new java.awt.CardLayout());
        pnlTong.add(dkpRight, java.awt.BorderLayout.CENTER);

        pnlTop.setBackground(new java.awt.Color(0, 102, 153));
        pnlTop.setPreferredSize(new java.awt.Dimension(1434, 60));

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_clock_35px.png"))); // NOI18N

        lblTime.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("00:00:00");

        pnlThaoTac.setBackground(new java.awt.Color(0, 102, 153));
        pnlThaoTac.setLayout(new javax.swing.BoxLayout(pnlThaoTac, javax.swing.BoxLayout.LINE_AXIS));

        btnXuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_minus_math_30px_1.png"))); // NOI18N
        btnXuong.setBorder(null);
        btnXuong.setContentAreaFilled(false);
        btnXuong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuong.setFocusPainted(false);
        btnXuong.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_minus_math_30px.png"))); // NOI18N
        btnXuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuongActionPerformed(evt);
            }
        });
        pnlThaoTac.add(btnXuong);

        btnFull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_full_screen_filled_30px.png"))); // NOI18N
        btnFull.setBorder(null);
        btnFull.setContentAreaFilled(false);
        btnFull.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFull.setFocusPainted(false);
        btnFull.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_full_screen_filled_30px_1.png"))); // NOI18N
        btnFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullActionPerformed(evt);
            }
        });
        pnlThaoTac.add(btnFull);

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_sign_30px_4.png"))); // NOI18N
        btnThoat.setBorder(null);
        btnThoat.setContentAreaFilled(false);
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.setFocusPainted(false);
        btnThoat.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_sign_30px_3.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnlThaoTac.add(btnThoat);

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_male_circle_35px.png"))); // NOI18N

        lblTenNguoiDung.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTenNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNguoiDung.setText("ADMIN");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(lblDongHo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addGap(93, 93, 93)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 728, Short.MAX_VALUE)
                .addComponent(pnlThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(pnlThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(lblDongHo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTenNguoiDung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlTong.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, 1471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMousePressed
        pnlHome.setBackground(paneClick);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlHomeMousePressed

    private void pnlBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneClick);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlBanHangMousePressed

    private void pnlHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseClicked
        dkpRight.removeAll();
        Home mau = new Home();
        dkpRight.add(mau).setVisible(true);
    }//GEN-LAST:event_pnlHomeMouseClicked

    private void pnlBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMouseClicked
        dkpRight.removeAll();
        BanHang ad = new BanHang();
        dkpRight.add(ad).setVisible(true);
    }//GEN-LAST:event_pnlBanHangMouseClicked

    private void pnlKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseClicked
        dkpRight.removeAll();
        KhachHang huy = new KhachHang();
        dkpRight.add(huy).setVisible(true);
    }//GEN-LAST:event_pnlKhachHangMouseClicked

    private void pnlKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneClick);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlKhachHangMousePressed

    private void pnlDaiLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDaiLyMouseClicked
        dkpRight.removeAll();
        DaiLy daily = new DaiLy();
        dkpRight.add(daily).setVisible(true);
    }//GEN-LAST:event_pnlDaiLyMouseClicked

    private void pnlDaiLyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDaiLyMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneClick);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlDaiLyMousePressed

    private void pnlKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMouseClicked
        dkpRight.removeAll();
        vitri = new page_ViTri();
        dkpRight.add(vitri);
        dkpRight.revalidate();
        dkpRight.repaint();
    }//GEN-LAST:event_pnlKhoMouseClicked

    private void pnlKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneClick);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlKhoMousePressed

    private void pnlLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLuongMouseClicked
        dkpRight.removeAll();
        Luong luong = new Luong();
        dkpRight.add(luong).setVisible(true);
    }//GEN-LAST:event_pnlLuongMouseClicked

    private void pnlLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLuongMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneClick);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlLuongMousePressed

    private void pnlTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaiKhoanMouseClicked
        dkpRight.removeAll();
        TTTaiKhoan taikhoan = new TTTaiKhoan();
        dkpRight.add(taikhoan).setVisible(true);
    }//GEN-LAST:event_pnlTaiKhoanMouseClicked

    private void pnlTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaiKhoanMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneClick);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlTaiKhoanMousePressed

    private void pnlBaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMouseClicked
        dkpRight.removeAll();
        BaoHanh bh = new BaoHanh();
        dkpRight.add(bh).setVisible(true);
    }//GEN-LAST:event_pnlBaoHanhMouseClicked

    private void pnlBaoHanhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneClick);
        pnlDoanhThu.setBackground(paneDefault);
    }//GEN-LAST:event_pnlBaoHanhMousePressed

    private void pnlDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMouseClicked
        dkpRight.removeAll();
        DoanhThu dt = new DoanhThu();
        dkpRight.add(dt).setVisible(true);
    }//GEN-LAST:event_pnlDoanhThuMouseClicked

    private void pnlDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMousePressed
        pnlHome.setBackground(paneDefault);
        pnlBanHang.setBackground(paneDefault);
        pnlKhachHang.setBackground(paneDefault);
        pnlDaiLy.setBackground(paneDefault);
        pnlKho.setBackground(paneDefault);
        pnlLuong.setBackground(paneDefault);
        pnlTaiKhoan.setBackground(paneDefault);
        pnlBaoHanh.setBackground(paneDefault);
        pnlDoanhThu.setBackground(paneClick);
    }//GEN-LAST:event_pnlDoanhThuMousePressed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuongActionPerformed
        setState(frmMain.ICONIFIED);
    }//GEN-LAST:event_btnXuongActionPerformed

    private void btnFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullActionPerformed
        if (maximized) {
            frmMain.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            frmMain.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }//GEN-LAST:event_btnFullActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void pnlBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMouseEntered
        whenMouseMoved(pnlBanHang, entercolor);
    }//GEN-LAST:event_pnlBanHangMouseEntered

    private void pnlBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMouseExited
        whenMouseMoved(pnlBanHang, exitcolor);
    }//GEN-LAST:event_pnlBanHangMouseExited
    public void whenMouseMoved(JPanel pnl, Color cl) {
        if (pnl.getBackground() == paneClick) {
            return;
        }
        pnl.setBackground(cl);
    }
    private void pnlKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseEntered
        whenMouseMoved(pnlKhachHang, entercolor);
    }//GEN-LAST:event_pnlKhachHangMouseEntered

    private void pnlKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseExited
        whenMouseMoved(pnlKhachHang, exitcolor);
    }//GEN-LAST:event_pnlKhachHangMouseExited

    private void pnlDaiLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDaiLyMouseEntered
        whenMouseMoved(pnlDaiLy, entercolor);
    }//GEN-LAST:event_pnlDaiLyMouseEntered

    private void pnlDaiLyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDaiLyMouseExited
        whenMouseMoved(pnlDaiLy, exitcolor);
    }//GEN-LAST:event_pnlDaiLyMouseExited

    private void pnlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseEntered
        whenMouseMoved(pnlHome, entercolor);
    }//GEN-LAST:event_pnlHomeMouseEntered

    private void pnlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseExited
        whenMouseMoved(pnlHome, exitcolor);
    }//GEN-LAST:event_pnlHomeMouseExited

    private void pnlKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMouseEntered
        whenMouseMoved(pnlKho, entercolor);
    }//GEN-LAST:event_pnlKhoMouseEntered

    private void pnlKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMouseExited
        whenMouseMoved(pnlKho, exitcolor);
    }//GEN-LAST:event_pnlKhoMouseExited

    private void pnlLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLuongMouseEntered
        whenMouseMoved(pnlLuong, entercolor);
    }//GEN-LAST:event_pnlLuongMouseEntered

    private void pnlLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLuongMouseExited
        whenMouseMoved(pnlLuong, exitcolor);
    }//GEN-LAST:event_pnlLuongMouseExited

    private void pnlTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaiKhoanMouseEntered
        whenMouseMoved(pnlTaiKhoan, entercolor);
    }//GEN-LAST:event_pnlTaiKhoanMouseEntered

    private void pnlTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaiKhoanMouseExited
        whenMouseMoved(pnlTaiKhoan, exitcolor);
    }//GEN-LAST:event_pnlTaiKhoanMouseExited

    private void pnlBaoHanhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMouseEntered
        whenMouseMoved(pnlBaoHanh, entercolor);
    }//GEN-LAST:event_pnlBaoHanhMouseEntered

    private void pnlBaoHanhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMouseExited
        whenMouseMoved(pnlBaoHanh, exitcolor);
    }//GEN-LAST:event_pnlBaoHanhMouseExited

    private void pnlDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMouseEntered
        whenMouseMoved(pnlDoanhThu, entercolor);
    }//GEN-LAST:event_pnlDoanhThuMouseEntered

    private void pnlDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMouseExited
        whenMouseMoved(pnlDoanhThu, exitcolor);
    }//GEN-LAST:event_pnlDoanhThuMouseExited
    int xx, yy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_formMouseDragged

    private void pnlSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseClicked
        pageMain = new page_Main_NhapHang();
        dkpRight.removeAll();
        dkpRight.add(pageMain);
        dkpRight.revalidate();
        dkpRight.repaint();
    }//GEN-LAST:event_pnlSanPhamMouseClicked

    private void pnlSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSanPhamMouseEntered

    private void pnlSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSanPhamMouseExited

    private void pnlSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSanPhamMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFull;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXuong;
    public static javax.swing.JDesktopPane dkpRight;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblBaoHanh;
    private javax.swing.JLabel lblDaiLy;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIconBanHang;
    private javax.swing.JLabel lblIconBaoHanh;
    private javax.swing.JLabel lblIconDaiLy;
    private javax.swing.JLabel lblIconDoanhThu;
    private javax.swing.JLabel lblIconDoanhThu1;
    private javax.swing.JLabel lblIconKH;
    private javax.swing.JLabel lblIconKho;
    private javax.swing.JLabel lblIconLuong;
    private javax.swing.JLabel lblIconTaiKhoan;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblLogoViTuan;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTenNguoiDung;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBanHang;
    private javax.swing.JPanel pnlBaoHanh;
    private javax.swing.JPanel pnlDaiLy;
    private javax.swing.JPanel pnlDoanhThu;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlKho;
    private javax.swing.JPanel pnlLuong;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlTaiKhoan;
    private javax.swing.JPanel pnlThaoTac;
    private javax.swing.JPanel pnlTong;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
