/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ChuyenDoi;
import DAO.DBConnection;
import java.awt.Color;
import java.util.Date;

/**
 *
 * @author Admin
 */
public class jdlAddNhaCungCap extends javax.swing.JDialog {
    /**
     * Creates new form jdlAddNhanVien
     */
    public jdlAddNhaCungCap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DBConnection conn = new DBConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrGioiTinh = new javax.swing.ButtonGroup();
        pnlChinh = new javax.swing.JPanel();
        pnlTieuDe = new javax.swing.JPanel();
        lblNhaCungCap = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        pnlIDNCC = new javax.swing.JPanel();
        lblIDNCC = new javax.swing.JLabel();
        lblTBIDNcc = new javax.swing.JLabel();
        txtIDNCC = new javax.swing.JTextField();
        pnlTenNCC = new javax.swing.JPanel();
        lblTenNCC = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        lblTBTenNCC = new javax.swing.JLabel();
        pnlLoaiHinh = new javax.swing.JPanel();
        lblLoaiHinh = new javax.swing.JLabel();
        txtLoaiHinh = new javax.swing.JTextField();
        lblTBLoaiHinh = new javax.swing.JLabel();
        pnlDiaChi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblTBDiaChi = new javax.swing.JLabel();
        pnlNhomNCC = new javax.swing.JPanel();
        lblNhomNCC = new javax.swing.JLabel();
        txtNhomNCC = new javax.swing.JTextField();
        lblTBNhomNCC = new javax.swing.JLabel();
        pnlSDT = new javax.swing.JPanel();
        lblSDT = new javax.swing.JLabel();
        lblTBSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JFormattedTextField();
        pnlMSThue = new javax.swing.JPanel();
        lblMSThue = new javax.swing.JLabel();
        txtMSThue = new javax.swing.JTextField();
        lblTBThue = new javax.swing.JLabel();
        pnlNguoiLH = new javax.swing.JPanel();
        lblNguoiLienHe = new javax.swing.JLabel();
        lblTBNguoiLH = new javax.swing.JLabel();
        txtNguoiLH = new javax.swing.JTextField();
        pnlEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblTBEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pnlTrangWeb = new javax.swing.JPanel();
        lblTrangWeb = new javax.swing.JLabel();
        lblTBTrangWeb = new javax.swing.JLabel();
        txtTrangWeb = new javax.swing.JTextField();
        pnlTrangWeb1 = new javax.swing.JPanel();
        lblTrangWeb1 = new javax.swing.JLabel();
        lblTBTKBank = new javax.swing.JLabel();
        txtTKBank = new javax.swing.JTextField();
        pnlTrangWeb2 = new javax.swing.JPanel();
        lblTenBank = new javax.swing.JLabel();
        lblTBTenBank = new javax.swing.JLabel();
        txtTenBank = new javax.swing.JTextField();
        pnlNgayThem = new javax.swing.JPanel();
        lblNgayThem = new javax.swing.JLabel();
        lblTBNgayThem = new javax.swing.JLabel();
        txtNgayThem = new javax.swing.JFormattedTextField();
        pnlGhiChu = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblTBGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÔNG TIN NHÀ CUNG CẤP");

        pnlChinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        pnlTieuDe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 153)));
        pnlTieuDe.setForeground(new java.awt.Color(0, 102, 153));

        lblNhaCungCap.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNhaCungCap.setForeground(new java.awt.Color(0, 102, 153));
        lblNhaCungCap.setText("THÊM MỚI NHÀ CUNG CẤP");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNhaCungCap)
                .addGap(20, 20, 20))
        );

        pnlChinh.add(pnlTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        btnThoat.setBackground(new java.awt.Color(255, 204, 0));
        btnThoat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_rewind_50px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.setBorder(null);
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThoatMouseExited(evt);
            }
        });
        pnlChinh.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 142, 47));

        pnlIDNCC.setBackground(new java.awt.Color(255, 255, 255));
        pnlIDNCC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        pnlIDNCC.setToolTipText("");

        lblIDNCC.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblIDNCC.setForeground(new java.awt.Color(0, 0, 0));
        lblIDNCC.setText("ID NCC (*)                         :");
        lblIDNCC.setMaximumSize(new java.awt.Dimension(115, 16));
        lblIDNCC.setMinimumSize(new java.awt.Dimension(115, 16));
        lblIDNCC.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBIDNcc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBIDNcc.setForeground(new java.awt.Color(153, 0, 0));
        lblTBIDNcc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtIDNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIDNCC.setBorder(null);

        javax.swing.GroupLayout pnlIDNCCLayout = new javax.swing.GroupLayout(pnlIDNCC);
        pnlIDNCC.setLayout(pnlIDNCCLayout);
        pnlIDNCCLayout.setHorizontalGroup(
            pnlIDNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIDNCCLayout.createSequentialGroup()
                .addComponent(lblIDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtIDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBIDNcc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlIDNCCLayout.setVerticalGroup(
            pnlIDNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIDNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblIDNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTBIDNcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlIDNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pnlTenNCC.setBackground(new java.awt.Color(255, 255, 255));
        pnlTenNCC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblTenNCC.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTenNCC.setForeground(new java.awt.Color(0, 0, 0));
        lblTenNCC.setText("TÊN NHÀ CUNG CẤP (*):");
        lblTenNCC.setMaximumSize(new java.awt.Dimension(115, 16));
        lblTenNCC.setMinimumSize(new java.awt.Dimension(115, 16));
        lblTenNCC.setPreferredSize(new java.awt.Dimension(115, 16));

        txtTenNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTenNCC.setBorder(null);

        lblTBTenNCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBTenNCC.setForeground(new java.awt.Color(153, 0, 0));
        lblTBTenNCC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlTenNCCLayout = new javax.swing.GroupLayout(pnlTenNCC);
        pnlTenNCC.setLayout(pnlTenNCCLayout);
        pnlTenNCCLayout.setHorizontalGroup(
            pnlTenNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTenNCCLayout.createSequentialGroup()
                .addComponent(lblTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTenNCCLayout.setVerticalGroup(
            pnlTenNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTenNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(lblTBTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlTenNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 500, -1));

        pnlLoaiHinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoaiHinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblLoaiHinh.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblLoaiHinh.setForeground(new java.awt.Color(0, 0, 0));
        lblLoaiHinh.setText("LOẠI HÌNH  (*)                  :");
        lblLoaiHinh.setMaximumSize(new java.awt.Dimension(115, 16));
        lblLoaiHinh.setMinimumSize(new java.awt.Dimension(115, 16));
        lblLoaiHinh.setPreferredSize(new java.awt.Dimension(115, 16));

        txtLoaiHinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLoaiHinh.setBorder(null);

        lblTBLoaiHinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBLoaiHinh.setForeground(new java.awt.Color(153, 0, 0));
        lblTBLoaiHinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlLoaiHinhLayout = new javax.swing.GroupLayout(pnlLoaiHinh);
        pnlLoaiHinh.setLayout(pnlLoaiHinhLayout);
        pnlLoaiHinhLayout.setHorizontalGroup(
            pnlLoaiHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiHinhLayout.createSequentialGroup()
                .addComponent(lblLoaiHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(txtLoaiHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBLoaiHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLoaiHinhLayout.setVerticalGroup(
            pnlLoaiHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoaiHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtLoaiHinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(lblTBLoaiHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 500, -1));

        pnlDiaChi.setBackground(new java.awt.Color(255, 255, 255));
        pnlDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ĐỊA CHỈ (*)                        :");
        jLabel5.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(115, 16));

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDiaChi.setBorder(null);

        lblTBDiaChi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBDiaChi.setForeground(new java.awt.Color(153, 0, 0));
        lblTBDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlDiaChiLayout = new javax.swing.GroupLayout(pnlDiaChi);
        pnlDiaChi.setLayout(pnlDiaChiLayout);
        pnlDiaChiLayout.setHorizontalGroup(
            pnlDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiaChiLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlDiaChiLayout.setVerticalGroup(
            pnlDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(lblTBDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 500, -1));

        pnlNhomNCC.setBackground(new java.awt.Color(255, 255, 255));
        pnlNhomNCC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblNhomNCC.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNhomNCC.setForeground(new java.awt.Color(0, 0, 0));
        lblNhomNCC.setText("NHÓM NCC (*)                :");
        lblNhomNCC.setMaximumSize(new java.awt.Dimension(115, 16));
        lblNhomNCC.setMinimumSize(new java.awt.Dimension(115, 16));
        lblNhomNCC.setPreferredSize(new java.awt.Dimension(115, 16));

        txtNhomNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNhomNCC.setBorder(null);

        lblTBNhomNCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBNhomNCC.setForeground(new java.awt.Color(153, 0, 0));
        lblTBNhomNCC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlNhomNCCLayout = new javax.swing.GroupLayout(pnlNhomNCC);
        pnlNhomNCC.setLayout(pnlNhomNCCLayout);
        pnlNhomNCCLayout.setHorizontalGroup(
            pnlNhomNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhomNCCLayout.createSequentialGroup()
                .addComponent(lblNhomNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(txtNhomNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBNhomNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNhomNCCLayout.setVerticalGroup(
            pnlNhomNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhomNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNhomNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(lblTBNhomNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlNhomNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 500, -1));

        pnlSDT.setBackground(new java.awt.Color(255, 255, 255));
        pnlSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblSDT.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 0));
        lblSDT.setText("SỐ ĐIỆN THOẠI  (*)        :");
        lblSDT.setMaximumSize(new java.awt.Dimension(115, 16));
        lblSDT.setMinimumSize(new java.awt.Dimension(115, 16));
        lblSDT.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBSDT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBSDT.setForeground(new java.awt.Color(153, 0, 0));
        lblTBSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtSDT.setBorder(null);
        try {
            txtSDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtSDT.setText("0000000000");
        txtSDT.setToolTipText("");
        txtSDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlSDTLayout = new javax.swing.GroupLayout(pnlSDT);
        pnlSDT.setLayout(pnlSDTLayout);
        pnlSDTLayout.setHorizontalGroup(
            pnlSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSDTLayout.createSequentialGroup()
                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTBSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSDTLayout.setVerticalGroup(
            pnlSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(pnlSDTLayout.createSequentialGroup()
                .addComponent(lblTBSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 500, -1));

        pnlMSThue.setBackground(new java.awt.Color(255, 255, 255));
        pnlMSThue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblMSThue.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblMSThue.setForeground(new java.awt.Color(0, 0, 0));
        lblMSThue.setText("MÃ SỐ THUẾ (*)              :");
        lblMSThue.setMaximumSize(new java.awt.Dimension(115, 16));
        lblMSThue.setMinimumSize(new java.awt.Dimension(115, 16));
        lblMSThue.setPreferredSize(new java.awt.Dimension(115, 16));

        txtMSThue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMSThue.setBorder(null);

        lblTBThue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBThue.setForeground(new java.awt.Color(153, 0, 0));
        lblTBThue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlMSThueLayout = new javax.swing.GroupLayout(pnlMSThue);
        pnlMSThue.setLayout(pnlMSThueLayout);
        pnlMSThueLayout.setHorizontalGroup(
            pnlMSThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMSThueLayout.createSequentialGroup()
                .addComponent(lblMSThue, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtMSThue, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBThue, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMSThueLayout.setVerticalGroup(
            pnlMSThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMSThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtMSThue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(lblTBThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlMSThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        pnlNguoiLH.setBackground(new java.awt.Color(255, 255, 255));
        pnlNguoiLH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        pnlNguoiLH.setToolTipText("");

        lblNguoiLienHe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNguoiLienHe.setForeground(new java.awt.Color(0, 0, 0));
        lblNguoiLienHe.setText("NGƯỜI LIÊN HỆ (*)           :");
        lblNguoiLienHe.setMaximumSize(new java.awt.Dimension(115, 16));
        lblNguoiLienHe.setMinimumSize(new java.awt.Dimension(115, 16));
        lblNguoiLienHe.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBNguoiLH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBNguoiLH.setForeground(new java.awt.Color(153, 0, 0));
        lblTBNguoiLH.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtNguoiLH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNguoiLH.setForeground(new java.awt.Color(0, 0, 0));
        txtNguoiLH.setBorder(null);

        javax.swing.GroupLayout pnlNguoiLHLayout = new javax.swing.GroupLayout(pnlNguoiLH);
        pnlNguoiLH.setLayout(pnlNguoiLHLayout);
        pnlNguoiLHLayout.setHorizontalGroup(
            pnlNguoiLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiLHLayout.createSequentialGroup()
                .addComponent(lblNguoiLienHe, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtNguoiLH, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBNguoiLH, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNguoiLHLayout.setVerticalGroup(
            pnlNguoiLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNguoiLienHe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNguoiLH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTBNguoiLH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlNguoiLH, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        pnlEmail.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        pnlEmail.setToolTipText("");

        lblEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("EMAIL                                   :");
        lblEmail.setMaximumSize(new java.awt.Dimension(115, 16));
        lblEmail.setMinimumSize(new java.awt.Dimension(115, 16));
        lblEmail.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBEmail.setForeground(new java.awt.Color(153, 0, 0));
        lblTBEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorder(null);

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTBEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        pnlTrangWeb.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrangWeb.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        pnlTrangWeb.setToolTipText("");

        lblTrangWeb.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTrangWeb.setForeground(new java.awt.Color(0, 0, 0));
        lblTrangWeb.setText("TRANG WEB                       :");
        lblTrangWeb.setMaximumSize(new java.awt.Dimension(115, 16));
        lblTrangWeb.setMinimumSize(new java.awt.Dimension(115, 16));
        lblTrangWeb.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBTrangWeb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBTrangWeb.setForeground(new java.awt.Color(153, 0, 0));
        lblTBTrangWeb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtTrangWeb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTrangWeb.setForeground(new java.awt.Color(0, 0, 0));
        txtTrangWeb.setBorder(null);

        javax.swing.GroupLayout pnlTrangWebLayout = new javax.swing.GroupLayout(pnlTrangWeb);
        pnlTrangWeb.setLayout(pnlTrangWebLayout);
        pnlTrangWebLayout.setHorizontalGroup(
            pnlTrangWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangWebLayout.createSequentialGroup()
                .addComponent(lblTrangWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtTrangWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBTrangWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTrangWebLayout.setVerticalGroup(
            pnlTrangWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTrangWeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTrangWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTBTrangWeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlTrangWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        pnlTrangWeb1.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrangWeb1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        pnlTrangWeb1.setToolTipText("");

        lblTrangWeb1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTrangWeb1.setForeground(new java.awt.Color(0, 0, 0));
        lblTrangWeb1.setText("TÀI KHOÀN NGÂN HÀNG :");
        lblTrangWeb1.setMaximumSize(new java.awt.Dimension(115, 16));
        lblTrangWeb1.setMinimumSize(new java.awt.Dimension(115, 16));
        lblTrangWeb1.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBTKBank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBTKBank.setForeground(new java.awt.Color(153, 0, 0));
        lblTBTKBank.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtTKBank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTKBank.setForeground(new java.awt.Color(0, 0, 0));
        txtTKBank.setBorder(null);

        javax.swing.GroupLayout pnlTrangWeb1Layout = new javax.swing.GroupLayout(pnlTrangWeb1);
        pnlTrangWeb1.setLayout(pnlTrangWeb1Layout);
        pnlTrangWeb1Layout.setHorizontalGroup(
            pnlTrangWeb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangWeb1Layout.createSequentialGroup()
                .addComponent(lblTrangWeb1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtTKBank, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBTKBank, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTrangWeb1Layout.setVerticalGroup(
            pnlTrangWeb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangWeb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTrangWeb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTKBank, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTBTKBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlTrangWeb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        pnlTrangWeb2.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrangWeb2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        pnlTrangWeb2.setToolTipText("");

        lblTenBank.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTenBank.setForeground(new java.awt.Color(0, 0, 0));
        lblTenBank.setText("TÊN NGÂN HÀNG             :");
        lblTenBank.setMaximumSize(new java.awt.Dimension(115, 16));
        lblTenBank.setMinimumSize(new java.awt.Dimension(115, 16));
        lblTenBank.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBTenBank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBTenBank.setForeground(new java.awt.Color(153, 0, 0));
        lblTBTenBank.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtTenBank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTenBank.setForeground(new java.awt.Color(0, 0, 0));
        txtTenBank.setBorder(null);

        javax.swing.GroupLayout pnlTrangWeb2Layout = new javax.swing.GroupLayout(pnlTrangWeb2);
        pnlTrangWeb2.setLayout(pnlTrangWeb2Layout);
        pnlTrangWeb2Layout.setHorizontalGroup(
            pnlTrangWeb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangWeb2Layout.createSequentialGroup()
                .addComponent(lblTenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtTenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBTenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTrangWeb2Layout.setVerticalGroup(
            pnlTrangWeb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangWeb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTenBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTenBank, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblTBTenBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlTrangWeb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        pnlNgayThem.setBackground(new java.awt.Color(255, 255, 255));
        pnlNgayThem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblNgayThem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNgayThem.setForeground(new java.awt.Color(0, 0, 0));
        lblNgayThem.setText("NGÀY THÊM                       :");
        lblNgayThem.setMaximumSize(new java.awt.Dimension(115, 16));
        lblNgayThem.setMinimumSize(new java.awt.Dimension(115, 16));
        lblNgayThem.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBNgayThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBNgayThem.setForeground(new java.awt.Color(153, 0, 0));
        lblTBNgayThem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtNgayThem.setBorder(null);
        txtNgayThem.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtNgayThem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNgayThem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNgayThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNgayThem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNgayThemCaretUpdate(evt);
            }
        });
        txtNgayThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayThemMouseClicked(evt);
            }
        });
        txtNgayThem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNgayThemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlNgayThemLayout = new javax.swing.GroupLayout(pnlNgayThem);
        pnlNgayThem.setLayout(pnlNgayThemLayout);
        pnlNgayThemLayout.setHorizontalGroup(
            pnlNgayThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayThemLayout.createSequentialGroup()
                .addComponent(lblNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNgayThemLayout.setVerticalGroup(
            pnlNgayThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNgayThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlNgayThemLayout.createSequentialGroup()
                .addComponent(lblTBNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlChinh.add(pnlNgayThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 500, -1));

        pnlGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        pnlGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblTrangThai.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(0, 0, 0));
        lblTrangThai.setText("GHI CHÚ                            :");
        lblTrangThai.setMaximumSize(new java.awt.Dimension(115, 16));
        lblTrangThai.setMinimumSize(new java.awt.Dimension(115, 16));
        lblTrangThai.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBGhiChu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBGhiChu.setForeground(new java.awt.Color(153, 0, 0));
        lblTBGhiChu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtGhiChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(0, 0, 0));
        txtGhiChu.setBorder(null);

        javax.swing.GroupLayout pnlGhiChuLayout = new javax.swing.GroupLayout(pnlGhiChu);
        pnlGhiChu.setLayout(pnlGhiChuLayout);
        pnlGhiChuLayout.setHorizontalGroup(
            pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGhiChuLayout.createSequentialGroup()
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTBGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlGhiChuLayout.setVerticalGroup(
            pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGhiChuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlGhiChuLayout.createSequentialGroup()
                .addGroup(pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTBGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlChinh.add(pnlGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, 40));

        btnXoa.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_50px.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(null);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        pnlChinh.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 120, 47));

        btnThem.setBackground(new java.awt.Color(0, 102, 153));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save_50px.png"))); // NOI18N
        btnThem.setText("LƯU");
        btnThem.setBorder(null);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlChinh.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 120, 47));

        btnCapNhat.setBackground(new java.awt.Color(0, 102, 153));
        btnCapNhat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_uninstalling_updates_50px_2.png"))); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.setBorder(null);
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseExited(evt);
            }
        });
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlChinh.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, -1, 47));

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 153));
        btnLamMoi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_refresh_50px.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.setBorder(null);
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseExited(evt);
            }
        });
        pnlChinh.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, -1, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseExited
        btnThoat.setBackground(new Color(255,204,0));
    }//GEN-LAST:event_btnThoatMouseExited

    private void btnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseEntered
        btnThoat.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnThoatMouseEntered

    private void txtNgayThemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNgayThemCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayThemCaretUpdate

    private void txtNgayThemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgayThemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayThemKeyReleased

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        btnXoa.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        btnXoa.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        btnThem.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        btnThem.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnCapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseEntered
        btnCapNhat.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnCapNhatMouseEntered

    private void btnCapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseExited
        btnCapNhat.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnCapNhatMouseExited

    private void btnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseEntered
        btnLamMoi.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnLamMoiMouseEntered

    private void btnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseExited
        btnLamMoi.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnLamMoiMouseExited

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        BLL.BLL_NhaCungCap.insert();
        this.dispose();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        BLL.BLL_NhaCungCap.update();
        this.dispose();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtNgayThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayThemMouseClicked
        Date date = new Date();
        txtNgayThem.setText(ChuyenDoi.GetNgay(date));
    }//GEN-LAST:event_txtNgayThemMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlAddNhaCungCap dialog = new jdlAddNhaCungCap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrGioiTinh;
    public static javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    public static javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIDNCC;
    private javax.swing.JLabel lblLoaiHinh;
    private javax.swing.JLabel lblMSThue;
    private javax.swing.JLabel lblNgayThem;
    private javax.swing.JLabel lblNguoiLienHe;
    private javax.swing.JLabel lblNhaCungCap;
    private javax.swing.JLabel lblNhomNCC;
    private javax.swing.JLabel lblSDT;
    public static javax.swing.JLabel lblTBDiaChi;
    public static javax.swing.JLabel lblTBEmail;
    public static javax.swing.JLabel lblTBGhiChu;
    public static javax.swing.JLabel lblTBIDNcc;
    public static javax.swing.JLabel lblTBLoaiHinh;
    public static javax.swing.JLabel lblTBNgayThem;
    public static javax.swing.JLabel lblTBNguoiLH;
    public static javax.swing.JLabel lblTBNhomNCC;
    public static javax.swing.JLabel lblTBSDT;
    public static javax.swing.JLabel lblTBTKBank;
    public static javax.swing.JLabel lblTBTenBank;
    public static javax.swing.JLabel lblTBTenNCC;
    public static javax.swing.JLabel lblTBThue;
    public static javax.swing.JLabel lblTBTrangWeb;
    private javax.swing.JLabel lblTenBank;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangWeb;
    private javax.swing.JLabel lblTrangWeb1;
    private javax.swing.JPanel pnlChinh;
    private javax.swing.JPanel pnlDiaChi;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlGhiChu;
    private javax.swing.JPanel pnlIDNCC;
    private javax.swing.JPanel pnlLoaiHinh;
    private javax.swing.JPanel pnlMSThue;
    private javax.swing.JPanel pnlNgayThem;
    private javax.swing.JPanel pnlNguoiLH;
    private javax.swing.JPanel pnlNhomNCC;
    private javax.swing.JPanel pnlSDT;
    private javax.swing.JPanel pnlTenNCC;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JPanel pnlTrangWeb;
    private javax.swing.JPanel pnlTrangWeb1;
    private javax.swing.JPanel pnlTrangWeb2;
    public static javax.swing.JTextField txtDiaChi;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtGhiChu;
    public static javax.swing.JTextField txtIDNCC;
    public static javax.swing.JTextField txtLoaiHinh;
    public static javax.swing.JTextField txtMSThue;
    public static javax.swing.JFormattedTextField txtNgayThem;
    public static javax.swing.JTextField txtNguoiLH;
    public static javax.swing.JTextField txtNhomNCC;
    public static javax.swing.JFormattedTextField txtSDT;
    public static javax.swing.JTextField txtTKBank;
    public static javax.swing.JTextField txtTenBank;
    public static javax.swing.JTextField txtTenNCC;
    public static javax.swing.JTextField txtTrangWeb;
    // End of variables declaration//GEN-END:variables
}
