/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class jdlAddNhanVien extends javax.swing.JDialog {
    public static String IDNhanVien1;
    /**
     * Creates new form jdlAddNhanVien
     */
    public jdlAddNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrGioiTinh = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        pnlChinh = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblTBHoTen = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lblTBSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JFormattedTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        lblTBCMND = new javax.swing.JLabel();
        txtCMND = new javax.swing.JFormattedTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblTBNgayCap = new javax.swing.JLabel();
        txtNgayCap = new com.toedter.calendar.JDateChooser();
        jPanel30 = new javax.swing.JPanel();
        lblNoiCap = new javax.swing.JLabel();
        lblTBNoiCap = new javax.swing.JLabel();
        txtNoiCapCMND = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        lblNgaySinh = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        lblNgay1 = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel26 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTBEmail = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtDC = new javax.swing.JTextField();
        lblTBDC = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lblTBLuong = new javax.swing.JLabel();
        txtLuong = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        lblTBKiQuy = new javax.swing.JLabel();
        txtKiQuy = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        pnlTieuDe = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        btnThoat1 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblHinhAnh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÔNG TIN NHÂN VIÊN");
        setUndecorated(true);

        pnlChinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("MÃ NHÂN VIÊN (*)  :");
        jLabel28.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel28.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel28.setPreferredSize(new java.awt.Dimension(115, 16));

        lblMaNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(153, 0, 0));
        lblMaNV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtMaNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(0, 0, 0));
        txtMaNV.setToolTipText("Mã gồm 5 kí tự!");
        txtMaNV.setBorder(null);
        txtMaNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaNVFocusLost(evt);
            }
        });
        txtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaNVKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("HỌ VÀ TÊN (*)        :");
        jLabel18.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel18.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel18.setPreferredSize(new java.awt.Dimension(115, 16));

        txtHoTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHoTen.setToolTipText("Họ tên là chữ bao gồm từ 5 đến 50 kí tự!");
        txtHoTen.setBorder(null);
        txtHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoTenFocusLost(evt);
            }
        });
        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoTenKeyReleased(evt);
            }
        });

        lblTBHoTen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBHoTen.setForeground(new java.awt.Color(153, 0, 0));
        lblTBHoTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lblTBHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnlChinh.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("SỐ ĐIỆN THOẠI (*)   :");

        lblTBSDT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBSDT.setForeground(new java.awt.Color(153, 0, 0));
        lblTBSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtSDT.setBorder(null);
        try {
            txtSDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtSDT.setText("0123456789");
        txtSDT.setToolTipText("Số điện thoại gồm 10 kí tự");
        txtSDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
            .addComponent(lblTBSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("CMND (*)             :");
        jLabel36.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel36.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel36.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBCMND.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBCMND.setForeground(new java.awt.Color(153, 0, 0));
        lblTBCMND.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtCMND.setBorder(null);
        try {
            txtCMND.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### ### ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCMND.setText("123456789");
        txtCMND.setToolTipText("CMND gồm 9 kí tự!");
        txtCMND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCMND.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCMNDFocusLost(evt);
            }
        });
        txtCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCMNDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTBCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCMND)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(lblTBCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("NGÀY CẤP              :");
        jLabel24.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel24.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel24.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBNgayCap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBNgayCap.setForeground(new java.awt.Color(153, 0, 0));
        lblTBNgayCap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtNgayCap.setDateFormatString("dd/MM/yyyy");
        txtNgayCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNgayCap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNgayCapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNgayCapFocusLost(evt);
            }
        });
        txtNgayCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNgayCapKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblTBNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNgayCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(lblTBNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlChinh.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblNoiCap.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNoiCap.setForeground(new java.awt.Color(0, 0, 0));
        lblNoiCap.setText("NƠI CẤP                 :");

        lblTBNoiCap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBNoiCap.setForeground(new java.awt.Color(153, 0, 0));
        lblTBNoiCap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtNoiCapCMND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNoiCapCMND.setToolTipText("Không được để trống!");
        txtNoiCapCMND.setBorder(null);
        txtNoiCapCMND.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoiCapCMNDFocusLost(evt);
            }
        });
        txtNoiCapCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoiCapCMNDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(lblNoiCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(txtNoiCapCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblTBNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTBNoiCap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lblNoiCap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiCapCMND))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pnlChinh.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblNgaySinh.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(0, 0, 0));
        lblNgaySinh.setText("NGÀY SINH (*) ");
        lblNgaySinh.setMaximumSize(new java.awt.Dimension(115, 16));
        lblNgaySinh.setMinimumSize(new java.awt.Dimension(115, 16));
        lblNgaySinh.setPreferredSize(new java.awt.Dimension(115, 16));

        lblGioiTinh.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(0, 0, 0));
        lblGioiTinh.setText("GIỚI TÍNH (*) ");
        lblGioiTinh.setMaximumSize(new java.awt.Dimension(115, 16));
        lblGioiTinh.setMinimumSize(new java.awt.Dimension(115, 16));
        lblGioiTinh.setPreferredSize(new java.awt.Dimension(115, 16));

        radNam.setBackground(new java.awt.Color(255, 255, 255));
        bgrGioiTinh.add(radNam);
        radNam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radNam.setForeground(new java.awt.Color(0, 0, 0));
        radNam.setSelected(true);
        radNam.setText("Nam");

        radNu.setBackground(new java.awt.Color(255, 255, 255));
        bgrGioiTinh.add(radNu);
        radNu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radNu.setForeground(new java.awt.Color(0, 0, 0));
        radNu.setText("Nữ");

        lblNgay1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNgay1.setForeground(new java.awt.Color(204, 0, 0));

        txtNgaySinh.setToolTipText("");
        txtNgaySinh.setDateFormatString("dd/MM/yyyy");
        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radNam)
                .addGap(18, 18, 18)
                .addComponent(radNu)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radNu))
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 40));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("EMAIL (*)              :");
        jLabel26.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel26.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel26.setPreferredSize(new java.awt.Dimension(115, 16));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.setToolTipText("Ví dụ: khoa@gmail.com");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        lblTBEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBEmail.setForeground(new java.awt.Color(153, 0, 0));
        lblTBEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblTBEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(lblTBEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnlChinh.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("ĐỊA CHỈ (*)            :");
        jLabel34.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel34.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel34.setPreferredSize(new java.awt.Dimension(115, 16));

        txtDC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDC.setToolTipText("Địa chỉ bao gồm từ 5 đến 100 kí tự!");
        txtDC.setBorder(null);
        txtDC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDCFocusLost(evt);
            }
        });
        txtDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDCKeyReleased(evt);
            }
        });

        lblTBDC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBDC.setForeground(new java.awt.Color(153, 0, 0));
        lblTBDC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblTBDC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addComponent(lblTBDC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(txtDC, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnlChinh.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("LƯƠNG                :");
        jLabel32.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel32.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel32.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBLuong.setForeground(new java.awt.Color(153, 0, 0));
        lblTBLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtLuong.setBorder(null);
        txtLuong.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtLuong.setToolTipText("Không được nhập chữ!");
        txtLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuongKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("VNĐ");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(56, 56, 56)
                .addComponent(lblTBLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(lblTBLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(txtLuong)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 470, -1));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("KÍ QUỸ                :");
        jLabel37.setMaximumSize(new java.awt.Dimension(115, 16));
        jLabel37.setMinimumSize(new java.awt.Dimension(115, 16));
        jLabel37.setPreferredSize(new java.awt.Dimension(115, 16));

        lblTBKiQuy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTBKiQuy.setForeground(new java.awt.Color(153, 0, 0));
        lblTBKiQuy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtKiQuy.setBorder(null);
        txtKiQuy.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtKiQuy.setToolTipText("Không được nhập chữ!");
        txtKiQuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtKiQuy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKiQuyKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("VNĐ");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKiQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(56, 56, 56)
                .addComponent(lblTBKiQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(lblTBKiQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(txtKiQuy)
        );

        pnlChinh.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 470, -1));

        pnlTieuDe.setBackground(new java.awt.Color(0, 102, 153));
        pnlTieuDe.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 51)));
        pnlTieuDe.setForeground(new java.awt.Color(0, 102, 153));
        pnlTieuDe.setPreferredSize(new java.awt.Dimension(1149, 50));

        lblTaiKhoan.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setText("THÊM MỚI NHÂN VIÊN");

        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_sign_30px_4.png"))); // NOI18N
        btnThoat1.setBorder(null);
        btnThoat1.setContentAreaFilled(false);
        btnThoat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat1.setFocusPainted(false);
        btnThoat1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_sign_30px_3.png"))); // NOI18N
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 609, Short.MAX_VALUE)
                .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addComponent(btnThoat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlChinh.add(pnlTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnXoa.setBackground(new java.awt.Color(0, 102, 153));
        btnXoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_trash_35px.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(null);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlChinh.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 100, 60));

        btnCapNhat.setBackground(new java.awt.Color(0, 102, 153));
        btnCapNhat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_uninstalling_updates_filled_35px.png"))); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.setBorder(null);
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseExited(evt);
            }
        });
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlChinh.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 130, 60));

        btnThem.setBackground(new java.awt.Color(0, 102, 153));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save_all_filled_35px.png"))); // NOI18N
        btnThem.setText("LƯU");
        btnThem.setBorder(null);
        btnThem.setHideActionText(true);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlChinh.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 100, 60));

        btnLamMoi.setBackground(new java.awt.Color(0, 102, 153));
        btnLamMoi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_synchronize_filled_35px.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.setBorder(null);
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseExited(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlChinh.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 120, 60));

        lblHinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblHinhAnh.setForeground(new java.awt.Color(0, 0, 0));
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HÌNH ẢNH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        lblHinhAnh.setMaximumSize(new java.awt.Dimension(15, 15));
        lblHinhAnh.setOpaque(true);
        lblHinhAnh.setPreferredSize(new java.awt.Dimension(15, 15));
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });
        pnlChinh.add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 280, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongKeyReleased
        txtLuong.setText(BLL.ChuyenDoi.doubleToString(BLL.ChuyenDoi.stringToDouble(txtLuong.getText())));
    }//GEN-LAST:event_txtLuongKeyReleased

    private void txtKiQuyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKiQuyKeyReleased
        txtKiQuy.setText(BLL.ChuyenDoi.doubleToString(BLL.ChuyenDoi.stringToDouble(txtKiQuy.getText())));
    }//GEN-LAST:event_txtKiQuyKeyReleased

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        BLL.BLL_NhanVien.refresh();
        btnThem.setEnabled(true);
        btnCapNhat.setEnabled(false);
        txtMaNV.setEditable(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseExited
        btnLamMoi.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnLamMoiMouseExited

    private void btnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseEntered
        btnLamMoi.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnLamMoiMouseEntered

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if(!BLL.BLL_NhanVien.update()){
            return;
        }
        
        this.dispose();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnCapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseExited
        btnCapNhat.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnCapNhatMouseExited

    private void btnCapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseEntered
        btnCapNhat.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnCapNhatMouseEntered

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(!BLL.BLL_NhanVien.insert()){
            return;
        }
        this.dispose();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        btnThem.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        btnThem.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        btnXoa.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        btnXoa.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        BLL.BLL_NhanVien.selectImage();
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    private void txtMaNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNVFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("MaNV")) {
            return;
        }
    }//GEN-LAST:event_txtMaNVFocusLost

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(!BLL.BLL_NhanVien.delete(TTTaiKhoan.tblNhanVien)){
            return;
        }
        BLL.BLL_NhanVien.loadBangNV("");
        this.dispose();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtHoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoTenFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("hoVaTen")) {
            return;
        }
    }//GEN-LAST:event_txtHoTenFocusLost

    private void txtMaNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyReleased
        BLL.BLL_NhanVien.kiemTra("MaNV");
    }//GEN-LAST:event_txtMaNVKeyReleased

    private void txtHoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyReleased
        BLL.BLL_NhanVien.kiemTra("hoVaTen");
    }//GEN-LAST:event_txtHoTenKeyReleased

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        BLL.BLL_NhanVien.kiemTra("SDT");
    }//GEN-LAST:event_txtSDTKeyReleased

    private void txtCMNDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCMNDKeyReleased
        BLL.BLL_NhanVien.kiemTra("cmnd");
    }//GEN-LAST:event_txtCMNDKeyReleased

    private void txtNoiCapCMNDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoiCapCMNDKeyReleased
        BLL.BLL_NhanVien.kiemTra("noicap");
    }//GEN-LAST:event_txtNoiCapCMNDKeyReleased

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        BLL.BLL_NhanVien.kiemTra("email");
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtDCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDCKeyReleased
        BLL.BLL_NhanVien.kiemTra("diachi");
    }//GEN-LAST:event_txtDCKeyReleased

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("SDT")) {
            return;
        }
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtCMNDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCMNDFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("cmnd")) {
            return;
        }
    }//GEN-LAST:event_txtCMNDFocusLost

    private void txtNoiCapCMNDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoiCapCMNDFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("noicap")) {
            return;
        }
    }//GEN-LAST:event_txtNoiCapCMNDFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("email")) {
            return;
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtDCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDCFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("diachi")) {
            return;
        }
    }//GEN-LAST:event_txtDCFocusLost

    private void txtNgayCapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgayCapKeyReleased
        BLL.BLL_NhanVien.kiemTra("ngaycapcm");
    }//GEN-LAST:event_txtNgayCapKeyReleased

    private void txtNgayCapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgayCapFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayCapFocusGained

    private void txtNgayCapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgayCapFocusLost
        if (evt.isTemporary()) {
            return;
        }
        if (!BLL.BLL_NhanVien.kiemTra("ngaycapcm")) {
            return;
        }
    }//GEN-LAST:event_txtNgayCapFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlAddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlAddNhanVien dialog = new jdlAddNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrGioiTinh;
    public static javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    public static javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXoa;
    public static javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel lblGioiTinh;
    public static javax.swing.JLabel lblHinhAnh;
    public static javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgay1;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNoiCap;
    public static javax.swing.JLabel lblTBCMND;
    public static javax.swing.JLabel lblTBDC;
    public static javax.swing.JLabel lblTBEmail;
    public static javax.swing.JLabel lblTBHoTen;
    public static javax.swing.JLabel lblTBKiQuy;
    public static javax.swing.JLabel lblTBLuong;
    public static javax.swing.JLabel lblTBNgayCap;
    public static javax.swing.JLabel lblTBNoiCap;
    public static javax.swing.JLabel lblTBSDT;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JPanel pnlChinh;
    private javax.swing.JPanel pnlTieuDe;
    public static javax.swing.JRadioButton radNam;
    public static javax.swing.JRadioButton radNu;
    public static javax.swing.JFormattedTextField txtCMND;
    public static javax.swing.JTextField txtDC;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtHoTen;
    public static javax.swing.JFormattedTextField txtKiQuy;
    public static javax.swing.JFormattedTextField txtLuong;
    public static javax.swing.JTextField txtMaNV;
    public static com.toedter.calendar.JDateChooser txtNgayCap;
    public static com.toedter.calendar.JDateChooser txtNgaySinh;
    public static javax.swing.JTextField txtNoiCapCMND;
    public static javax.swing.JFormattedTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
