/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ChuyenDoi;
import DTO.MyComboBox;
import GUI.ViTri.HeaderColor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author bumte
 */
public class page_BanHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form page_BanHang
     */
    public page_BanHang() {
        initComponents();
        tblHoaDon.getTableHeader().setDefaultRenderer(new HeaderColor());
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHoaDon = new javax.swing.JPanel();
        pnlBanHang = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCTHoaDon = new javax.swing.JTable();
        pnlAddPnl = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtIDKH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDC = new javax.swing.JTextArea();
        txtSDT = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        txtTenKH = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCacGoiBaoHanh = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        txtMaVach = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtBarcode = new javax.swing.JTextField();
        cbb = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTenSP = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtThongTinSanPham = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        btnThemVaoHoaDon = new javax.swing.JButton();
        btnLuuHD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        lblTongTien = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        pnlHoaDon.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1466, Short.MAX_VALUE)
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        pnlBanHang.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnlBanHangLayout = new javax.swing.GroupLayout(pnlBanHang);
        pnlBanHang.setLayout(pnlBanHangLayout);
        pnlBanHangLayout.setHorizontalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addGroup(pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBanHangLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBanHangLayout.createSequentialGroup()
                        .addGap(702, 702, 702)
                        .addComponent(jLabel1)))
                .addContainerGap(723, Short.MAX_VALUE))
        );
        pnlBanHangLayout.setVerticalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        tblCTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Mã chi tiết phiếu nhập", "Mã vạch"
            }
        ));
        jScrollPane6.setViewportView(tblCTHoaDon);

        setBackground(new java.awt.Color(255, 255, 255));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        pnlAddPnl.setPreferredSize(new java.awt.Dimension(1510, 900));
        pnlAddPnl.setLayout(new java.awt.BorderLayout());

        pnlMain.setBackground(new java.awt.Color(102, 102, 0));
        pnlMain.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 300));

        tblHoaDon.setBackground(new java.awt.Color(238, 238, 238));
        tblHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Đơn giá", "Số lượng", "Tổng tiền", "Gói bảo hành", "Barcode", "Mã vạch", "seri", "ID Chi tiét phiếu nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setFillsViewportHeight(true);
        tblHoaDon.setGridColor(new java.awt.Color(51, 51, 51));
        tblHoaDon.setRowHeight(40);
        tblHoaDon.setSelectionBackground(new java.awt.Color(255, 102, 0));
        tblHoaDon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblHoaDonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(0).setMinWidth(50);
            tblHoaDon.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblHoaDon.getColumnModel().getColumn(0).setMaxWidth(50);
            tblHoaDon.getColumnModel().getColumn(2).setMinWidth(70);
            tblHoaDon.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblHoaDon.getColumnModel().getColumn(2).setMaxWidth(200);
            tblHoaDon.getColumnModel().getColumn(3).setMinWidth(50);
            tblHoaDon.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblHoaDon.getColumnModel().getColumn(3).setMaxWidth(100);
            tblHoaDon.getColumnModel().getColumn(4).setMinWidth(100);
            tblHoaDon.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblHoaDon.getColumnModel().getColumn(4).setMaxWidth(200);
            tblHoaDon.getColumnModel().getColumn(5).setMinWidth(120);
            tblHoaDon.getColumnModel().getColumn(5).setPreferredWidth(120);
            tblHoaDon.getColumnModel().getColumn(5).setMaxWidth(120);
            tblHoaDon.getColumnModel().getColumn(6).setMinWidth(120);
            tblHoaDon.getColumnModel().getColumn(6).setPreferredWidth(150);
            tblHoaDon.getColumnModel().getColumn(6).setMaxWidth(200);
            tblHoaDon.getColumnModel().getColumn(7).setMinWidth(0);
            tblHoaDon.getColumnModel().getColumn(7).setPreferredWidth(0);
            tblHoaDon.getColumnModel().getColumn(7).setMaxWidth(0);
            tblHoaDon.getColumnModel().getColumn(8).setMinWidth(0);
            tblHoaDon.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblHoaDon.getColumnModel().getColumn(8).setMaxWidth(0);
            tblHoaDon.getColumnModel().getColumn(9).setMinWidth(0);
            tblHoaDon.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblHoaDon.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        pnlMain.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1510, 620));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(241, 241, 241));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Thông tin khách hàng", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 616));

        txtIDKH.setBackground(new java.awt.Color(241, 241, 241));
        txtIDKH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtIDKH.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Mã khách hàng", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 18), new java.awt.Color(153, 0, 0))); // NOI18N
        txtIDKH.setMinimumSize(new java.awt.Dimension(445, 50));
        txtIDKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDKHFocusLost(evt);
            }
        });
        txtIDKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDKHActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(241, 241, 241));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), "Địa chỉ", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txtDC.setBackground(new java.awt.Color(241, 241, 241));
        txtDC.setColumns(20);
        txtDC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDC.setRows(5);
        txtDC.setBorder(null);
        jScrollPane1.setViewportView(txtDC);

        txtSDT.setBackground(new java.awt.Color(241, 241, 241));
        txtSDT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Số điện thoại", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 18), new java.awt.Color(153, 0, 0))); // NOI18N
        txtSDT.setFocusCycleRoot(true);
        txtSDT.setPreferredSize(new java.awt.Dimension(445, 50));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(241, 241, 241));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Thông tin thêm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(241, 241, 241));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));

        radNam.setBackground(new java.awt.Color(241, 241, 241));
        buttonGroup1.add(radNam);
        radNam.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        radNam.setSelected(true);
        radNam.setText("Nam");

        radNu.setBackground(new java.awt.Color(241, 241, 241));
        buttonGroup1.add(radNu);
        radNu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        radNu.setText("Nữ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radNam)
                .addGap(18, 18, 18)
                .addComponent(radNu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTenKH.setBackground(new java.awt.Color(241, 241, 241));
        txtTenKH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTenKH.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Tên khách hàng", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 18))); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(241, 241, 241));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Email", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 18))); // NOI18N

        txtNgaySinh.setDateFormatString("dd/MM/yyyy");
        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(txtIDKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtIDKH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(249, 249, 249));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Thông tin sản phẩm", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(800, 400));

        txtCacGoiBaoHanh.setBackground(new java.awt.Color(249, 249, 249));
        txtCacGoiBaoHanh.setColumns(20);
        txtCacGoiBaoHanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCacGoiBaoHanh.setLineWrap(true);
        txtCacGoiBaoHanh.setRows(5);
        txtCacGoiBaoHanh.setText("\n");
        txtCacGoiBaoHanh.setWrapStyleWord(true);
        txtCacGoiBaoHanh.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        txtCacGoiBaoHanh.setFocusable(false);
        jScrollPane4.setViewportView(txtCacGoiBaoHanh);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Thêm gói bảo hành mới");

        jTabbedPane1.setBackground(new java.awt.Color(249, 249, 249));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(249, 249, 249));

        txtMaVach.setBackground(new java.awt.Color(249, 249, 249));
        txtMaVach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMaVach.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Mã SKU/Mã vạch", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 18), new java.awt.Color(153, 0, 0))); // NOI18N
        txtMaVach.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaVachFocusLost(evt);
            }
        });
        txtMaVach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaVachActionPerformed(evt);
            }
        });

        txtGiamGia.setBackground(new java.awt.Color(249, 249, 249));
        txtGiamGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGiamGia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Giảm giá", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 18))); // NOI18N
        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });

        txtGiaBan.setBackground(new java.awt.Color(249, 249, 249));
        txtGiaBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGiaBan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Giá bán", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 18))); // NOI18N
        txtGiaBan.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtGiaBanCaretUpdate(evt);
            }
        });
        txtGiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaBanKeyReleased(evt);
            }
        });

        txtBarcode.setBackground(new java.awt.Color(249, 249, 249));
        txtBarcode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtBarcode.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Barcode", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 18))); // NOI18N

        cbb.setBackground(new java.awt.Color(249, 249, 249));
        cbb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbbAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbbFocusLost(evt);
            }
        });
        cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbActionPerformed(evt);
            }
        });

        jScrollPane5.setBackground(new java.awt.Color(249, 249, 249));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)), "Tên sản phẩm", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 18))); // NOI18N

        txtTenSP.setBackground(new java.awt.Color(249, 249, 249));
        txtTenSP.setColumns(20);
        txtTenSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTenSP.setLineWrap(true);
        txtTenSP.setRows(5);
        txtTenSP.setWrapStyleWord(true);
        txtTenSP.setBorder(null);
        jScrollPane5.setViewportView(txtTenSP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaVach)
                    .addComponent(txtBarcode)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(txtGiaBan)
                    .addComponent(txtGiamGia)
                    .addComponent(cbb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaVach, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Thông tin sản phẩm", jPanel7);

        txtThongTinSanPham.setBackground(new java.awt.Color(249, 249, 249));
        txtThongTinSanPham.setColumns(20);
        txtThongTinSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtThongTinSanPham.setLineWrap(true);
        txtThongTinSanPham.setRows(5);
        txtThongTinSanPham.setWrapStyleWord(true);
        jScrollPane7.setViewportView(txtThongTinSanPham);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thông số kĩ thuật", jPanel8);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Thông tin sản phẩm");

        jPanel2.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(700, 620));

        btnThemVaoHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThemVaoHoaDon.setText("Thêm vào hóa đơn");
        btnThemVaoHoaDon.setEnabled(false);
        btnThemVaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoHoaDonActionPerformed(evt);
            }
        });

        btnLuuHD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLuuHD.setText("Lưu hóa đơn");
        btnLuuHD.setEnabled(false);
        btnLuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHDActionPerformed(evt);
            }
        });

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setEnabled(false);
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        lblTongTien.setBackground(new java.awt.Color(153, 153, 153));
        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(204, 0, 51));
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien.setText("20,000,000");
        lblTongTien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "TỔNG TIỀN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 51))); // NOI18N
        lblTongTien.setOpaque(true);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLuuHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemVaoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(31, 31, 31)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 527, Short.MAX_VALUE)
                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(btnThemVaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnLuuHD)
                    .addGap(27, 27, 27)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel9);

        pnlMain.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pnlAddPnl.add(pnlMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlAddPnl, java.awt.BorderLayout.CENTER);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        title.setPreferredSize(new java.awt.Dimension(1466, 30));
        title.setLayout(new javax.swing.BoxLayout(title, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Hóa đơn");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        title.add(jButton1);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Bán hàng");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        title.add(jButton2);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("main");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        title.add(jButton3);

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Thêm khách hàng mới");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        title.add(jButton4);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        title.add(jPanel4);

        getContentPane().add(title, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addPNL(pnlHoaDon);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addPNL(pnlBanHang);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        addPNL(pnlMain);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       txtSDT.requestFocus();

        BLL.BLL_BanHang.open();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbbAncestorAdded
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbb.getModel();
        cbbModel.removeAllElements();
        ResultSet rs = DAO.select.BHKhachHang(true);
        cbbModel.addElement("----Chọn gói bảo hành----");
        try {
            while (rs.next()) {
                String name = rs.getString("IDBHKH");
                cbbModel.addElement(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(page_BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbbAncestorAdded

    private void tblHoaDonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblHoaDonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDonAncestorAdded

    private void txtMaVachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaVachActionPerformed
        if (BLL.BLL_BanHang.layThongTinSP(txtMaVach.getText())) {
           cbb.requestFocus();
        }
        
    }//GEN-LAST:event_txtMaVachActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        if ( BLL.BLL_BanHang.showThongTinKhachHang(txtSDT.getText())) {
            txtMaVach.requestFocus();
        }

    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnThemVaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoHoaDonActionPerformed
        BLL.BLL_BanHang.loadThongTinHangTonKho(txtMaVach.getText());
        BLL.BLL_BanHang.setTongTien();
        btnLuuHD.setEnabled(true);
        btnThanhToan.setEnabled(true);
    }//GEN-LAST:event_btnThemVaoHoaDonActionPerformed

    private void btnLuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHDActionPerformed
       BLL.BLL_BanHang.luuHoaDon(false);
       fresh();
    }//GEN-LAST:event_btnLuuHDActionPerformed

    private void txtIDKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKHActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jdlAddKhachHang jdl = new jdlAddKhachHang(new JFrame(), true);
       jdl.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (!BLL.BLL_BanHang.thanhToan()) {
            ThongBao.ThongBao("Chưa thanh toán đc hóa đơn", "Thông báo");
            return;
            
        }
        ThongBao.ThongBao("Đã thanh toán hóa đơn", "Thông báo");
        lblTongTien.setText("0đ");
        tblCTHoaDon.repaint();
        tblCTHoaDon.revalidate();
        tblHoaDon.repaint();
        tblHoaDon.revalidate();
        fresh();
        
        
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtMaVachFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaVachFocusLost
        if (txtMaVach.getText().trim().isEmpty() || txtSDT.getText().trim().isEmpty() || cbb.getSelectedIndex() == 0) {
           btnThemVaoHoaDon.setEnabled(false);
            
        }else{
            btnThemVaoHoaDon.setEnabled(true);
        }
    }//GEN-LAST:event_txtMaVachFocusLost

    private void txtIDKHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDKHFocusLost
         if (txtMaVach.getText().trim().isEmpty() || txtSDT.getText().trim().isEmpty() || cbb.getSelectedIndex() == 0) {
           btnThemVaoHoaDon.setEnabled(false);
            
        }else{
            btnThemVaoHoaDon.setEnabled(true);
        }
    }//GEN-LAST:event_txtIDKHFocusLost

    private void cbbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbFocusLost
        if (txtMaVach.getText().trim().isEmpty() || txtSDT.getText().trim().isEmpty() || cbb.getSelectedIndex() == 0) {
           btnThemVaoHoaDon.setEnabled(false);
            
        }else{
            btnThemVaoHoaDon.setEnabled(true);
        }
    }//GEN-LAST:event_cbbFocusLost

    private void cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbActionPerformed
        if (cbb.getSelectedIndex() == 0) {
            ThongBao.ThongBao("Cần chọn gói bảo hành", "Thông báo");
        }else{
            btnThemVaoHoaDon.requestFocus();
        }
    }//GEN-LAST:event_cbbActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        if (evt.getClickCount() == 2) {
           XoaHoaDon jdl = new XoaHoaDon(new JFrame(),true);
           jdl.setVisible(true);
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtGiaBanCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtGiaBanCaretUpdate
        if (tblCTHoaDon.getRowCount() > 0) {
             BLL.BLL_BanHang.setTongTien();
        }else{
            lblTongTien.setText(txtGiaBan.getText());
        }
    }//GEN-LAST:event_txtGiaBanCaretUpdate

    private void txtGiaBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaBanKeyReleased
       txtGiaBan.setText(ChuyenDoi.doubleToString(ChuyenDoi.stringToDouble(txtGiaBan.getText())));
    }//GEN-LAST:event_txtGiaBanKeyReleased
    public void addPNL(JPanel pnl) {
        pnlAddPnl.removeAll();
        pnlAddPnl.add(pnl);
        BLL.BLL_BanHang.open();
        pnlAddPnl.revalidate();
        pnlAddPnl.repaint();

    }
    public void fresh(){
        txtBarcode.setText("");
        txtDC.setText("");
        txtEmail.setText("");
        txtGiaBan.setText("");
        txtGiamGia.setText("");
        txtIDKH.setText("");
        txtMaVach.setText("");
        txtNgaySinh.setDate(new Date());
        txtSDT.setText("");
        txtTenKH.setText("");
        txtTenSP.setText("");
        txtThongTinSanPham.setText("");
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuHD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemVaoHoaDon;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox cbb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnlAddPnl;
    private javax.swing.JPanel pnlBanHang;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlMain;
    public static javax.swing.JRadioButton radNam;
    public static javax.swing.JRadioButton radNu;
    public static javax.swing.JTable tblCTHoaDon;
    public static javax.swing.JTable tblHoaDon;
    private javax.swing.JPanel title;
    public static javax.swing.JTextField txtBarcode;
    public static javax.swing.JTextArea txtCacGoiBaoHanh;
    public static javax.swing.JTextArea txtDC;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtGiaBan;
    public static javax.swing.JTextField txtGiamGia;
    public static javax.swing.JTextField txtIDKH;
    public static javax.swing.JTextField txtMaVach;
    public static com.toedter.calendar.JDateChooser txtNgaySinh;
    public static javax.swing.JTextField txtSDT;
    public static javax.swing.JTextField txtTenKH;
    public static javax.swing.JTextArea txtTenSP;
    public static javax.swing.JTextArea txtThongTinSanPham;
    // End of variables declaration//GEN-END:variables
}
